language: java

before_install:
  - chmod -R +x src 
  - chmod +x gradlew

script: ./gradlew clean build
deploy:
    provider: script
    script: ./gradlew :lib:bintrayUpload -PbintrayUser=$BINTRAY_USER -PbintrayApiKey=$BINTRAY_KEY
    on: 
branch: master
